import type { LiveResponse } from "../lib/types";

export function LiveJourney({ live, onStart, onStop, busy, canOperate = true }: { live: LiveResponse | null; onStart: () => void; onStop: () => void; busy: boolean; canOperate?: boolean }) {
  const started = Boolean(live?.telemetry.started);
  const buffer = live?.state.buffer_size ?? 0;
  const required = live?.state.buffer_required ?? 10;
  const steps = ["Traffic", "Flows", "Network states", `${buffer} / ${required} states`, "Forecast"];
  return <section className="live-journey section-block" aria-labelledby="live-journey-heading"><div className="section-heading"><div><p className="overline">Live network</p><h2 id="live-journey-heading">Monitor this machine.</h2></div></div><div className="live-explain"><div><strong>Live network traffic</strong><p>Sentinel observes network traffic metadata from the selected interface and continuously builds 10-second network states. Packet payload contents are not retained.</p><div className="live-actions">{canOperate ? <><button onClick={onStart} disabled={busy || started}>{busy ? "Connecting…" : started ? "Live monitoring active" : "Start live monitoring"}</button><button className="button-quiet" onClick={onStop} disabled={busy || !started}>Stop live monitoring</button></> : <span className="simulation-lock">VIEWER ROLE · LIVE CONTROL REQUIRES OPERATOR ACCESS</span>}</div></div><div className="live-next"><span className="overline">What happens next</span><div className="journey-steps">{steps.map((step, index) => <span className={index <= (started ? 1 : 0) ? "step-active" : ""} key={step}>{step}{index < steps.length - 1 && <b>→</b>}</span>)}</div><small>{buffer < required ? `Building forecast history — Sentinel needs ${required} recent states before it can forecast.` : "Enough history is available. Future network-state forecasting is active."}</small></div></div></section>;
}
